/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/feeds/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 피드 상세 조회
         * @description 피드 ID로 상세 정보를 조회합니다.
         */
        get: operations["getFeed"];
        /**
         * 피드 수정
         * @description 기존 피드를 수정합니다.
         */
        put: operations["updateFeed"];
        post?: never;
        /**
         * 피드 삭제
         * @description 피드를 삭제합니다.
         */
        delete: operations["deleteFeed"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveFcmToken"];
        delete: operations["deleteFcmToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 피드 목록 조회
         * @description 조건에 따라 피드 목록을 조회합니다.
         */
        get: operations["getFeeds"];
        put?: never;
        /**
         * 피드 생성
         * @description 새로운 피드를 생성합니다.
         */
        post: operations["createFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{feedId}/participations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 참가자 목록 조회
         * @description 특정 피드의 전체 참가자 목록을 조회합니다.
         */
        get: operations["getParticipations"];
        put?: never;
        /**
         * 참가 신청
         * @description 특정 피드에 참가 신청을 합니다.
         */
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{feedId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 댓글 목록 조회
         * @description 특정 피드의 댓글 목록을 조회합니다.
         */
        get: operations["getComments"];
        put?: never;
        /**
         * 댓글/대댓글 작성
         * @description 특정 피드에 댓글 또는 대댓글을 작성합니다.
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participations/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 참가 거절
         * @description 참가 신청을 거절합니다.
         */
        patch: operations["reject"];
        trace?: never;
    };
    "/api/participations/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 참가 승인
         * @description 참가 신청을 승인합니다.
         */
        patch: operations["approve"];
        trace?: never;
    };
    "/api/members/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateNickname"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/s3/presigned-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPreSignedUploadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyNotifications"];
        put?: never;
        post?: never;
        delete: operations["deleteMyNotifications"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/participations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 경기 참가 기록 조회 (커서 기반 무한 스크롤)
         * @description 로그인한 사용자의 경기 참가 기록을 조회합니다.
         *
         *     - cursorTime, cursorId가 없으면 최초 조회
         *     - cursorTime, cursorId가 있으면 다음 페이지 조회
         *     - status 파라미터로 참가 상태별 필터링 가능
         *     - 정렬 기준: createdAt DESC, id DESC
         */
        get: operations["getMyParticipations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{feedId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 댓글 삭제
         * @description 댓글 ID를 기준으로 댓글을 삭제합니다.
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FeedUpdateRequest: {
            title?: string;
            image?: string;
            description?: string;
            /** Format: int32 */
            timer?: number;
            playGround?: string;
            /** Format: date-time */
            playDate?: string;
            /** Format: int32 */
            round?: number;
            address?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            allNull?: boolean;
        };
        FcmTokenRequest: {
            fcmToken: string;
        };
        FeedCreateRequest: {
            image?: string;
            title: string;
            playGround: string;
            /** Format: date-time */
            playDate: string;
            /** Format: int32 */
            round?: number;
            /** Format: int32 */
            playCount?: number;
            description?: string;
            /** Format: int32 */
            timer?: number;
            address?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
        };
        CommentCreateRequest: {
            description: string;
            /** Format: int64 */
            parentId?: number;
        };
        NicknameUpdateRequest: {
            nickname: string;
        };
        NotificationResponse: {
            /** Format: int64 */
            notificationId?: number;
            message?: string;
            read?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** @enum {string} */
            targetType?: "PARTICIPATION_APPROVED" | "PARTICIPATION_REJECTED" | "GAME_STARTED" | "GAME_FINISHED";
            /** Format: int64 */
            targetId?: number;
        };
        MyParticipationResponse: {
            /** Format: int64 */
            participationId?: number;
            /** Format: int64 */
            feedId?: number;
            feedTitle?: string;
            playGround?: string;
            /** Format: date-time */
            playDate?: string;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELED";
        };
        FeedCursorResponse: {
            feeds?: components["schemas"]["FeedResponse"][];
            /** Format: int64 */
            nextCursorId?: number;
            /** Format: date-time */
            nextCursorCreatedAt?: string;
            hasNext?: boolean;
        };
        FeedResponse: {
            /** Format: int64 */
            feedId?: number;
            title?: string;
            image?: string;
            playGround?: string;
            /** Format: date-time */
            playDate?: string;
            /** Format: int32 */
            playCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        FeedDetailResponse: {
            /** Format: int64 */
            feedId?: number;
            image?: string;
            title?: string;
            playGround?: string;
            /** Format: date-time */
            playDate?: string;
            /** Format: int32 */
            round?: number;
            /** Format: int32 */
            playCount?: number;
            description?: string;
            /** Format: int32 */
            timer?: number;
            writer?: components["schemas"]["WriterResponse"];
        };
        WriterResponse: {
            /** Format: int64 */
            writerId?: number;
            nickname?: string;
        };
        ParticipationResponse: {
            /** Format: int64 */
            participationId?: number;
            /** Format: int64 */
            applicantId?: number;
            applicantNickname?: string;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED" | "CANCELED";
            /** Format: date-time */
            appliedAt?: string;
        };
        CommentResponse: {
            /** Format: int64 */
            commentId?: number;
            description?: string;
            /** Format: int64 */
            parentId?: number;
            /** Format: int32 */
            depth?: number;
            commentType?: string;
            /** Format: int64 */
            memberId?: number;
            nickname?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 피드 ID */
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 피드 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedDetailResponse"];
                };
            };
        };
    };
    updateFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 피드 ID */
                feedId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedUpdateRequest"];
            };
        };
        responses: {
            /** @description 피드 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 피드 ID */
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 피드 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveFcmToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FcmTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteFcmToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFeeds: {
        parameters: {
            query?: {
                /** @description 커서 ID */
                cursorId?: number;
                /** @description 커서 생성 시간 */
                cursorCreatedAt?: string;
                /** @description 정렬 기준 (LATEST / DISTANCE) */
                sort?: string;
                /** @description 위도 */
                latitude?: number;
                /** @description 경도 */
                longitude?: number;
                /** @description 조회 개수 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 피드 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedCursorResponse"];
                };
            };
        };
    };
    createFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedCreateRequest"];
            };
        };
        responses: {
            /** @description 피드 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    getParticipations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 피드 ID */
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참가자 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipationResponse"][];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 피드 ID */
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참가 신청 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 피드 ID */
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 댓글 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentResponse"][];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 피드 ID */
                feedId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description 댓글 작성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 참가 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참가 거절 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 참가 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참가 승인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NicknameUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getPreSignedUploadUrl: {
        parameters: {
            query: {
                type: string;
                contentType: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getMyNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationResponse"][];
                };
            };
        };
    };
    deleteMyNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyParticipations: {
        parameters: {
            query?: {
                /** @description 참가 상태 (PENDING, APPROVED, REJECTED) */
                status?: string;
                /** @description 커서 기준 시간 (마지막 요소의 createdAt) */
                cursorTime?: string;
                /** @description 커서 기준 ID (마지막 요소의 id) */
                cursorId?: number;
                /** @description 조회 개수 (기본값 10) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 내 경기 참가 기록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MyParticipationResponse"][];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 댓글 ID */
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 댓글 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
